### ISSUE TITLE
Support for interface names (path element key value) which include ":" or spaces

### ISSUE THREAD

**Issue by krishprasad525** [karimra/gnmic#324] opened 2021-02-28 17:24 UTC
For any gnmi query with interface having the format of  ethernet1/1:1 , gets the following error:
Error: path parse error: malformed xpath
if I'm missing any option, let me know.

**Comment by karimra** [comment] 2021-03-01 11:29
Hi, can you share the full command for which you are getting this error?

**Comment by krishprasad525** [comment] 2021-03-01 16:37
Hi ,

It's a simple query for getting the interface parameters.Following is the
query:

gnmic -a <ip> -u <username>  -p <pass>  --tls-ca cert.pem --format jason
get --path interfaces/interface[name="ethernet 1/2:1"]

**Comment by karimra** [comment] 2021-03-02 08:52
@krishprasad525 can you give it a try with the latest release?
The issue was that the path parsing function looks for a `:` to determine if an origin is defined in the path.
I changed it to look for origin in the first path element only.

BTW, if your intention is to include the quotes in the interface name, use single quotes for the whole path:
`gnmic get --path 'interfaces/interface[name="ethernet 1/2:1"]'`

**Comment by krishprasad525** [comment] 2021-03-02 21:19
Thank you. It's working fine with  : 'interfaces/interface[name=ethernet 1/2:1]', but --debug is not showing the detail information. Can you please take a look.

Also, can we get the same implementation in gnmic prompt:
1. To accept the interfaces like "Ethernet 1/2" (with space between Ethernet and Port)
2. To accept interface with "Ethernet 1/2:1" (with space between Ethernet and port + colun in port number)
It gives the following error:
Error: path parse error: malformed xpath

**Comment by karimra** [comment] 2021-03-03 05:17
Can you detail what you expect to see with debug enabled?

Good catch for prompt mode, the culprit is the space in this case,
the prompt args are parsed with a naive split by space, changed it to consider quotes and double quotes.

Should be fixed by #328

**Comment by krishprasad525** [comment] 2021-03-03 05:40
Thank you for fixing the issue from prompt. 
Earlier debug output displayed all the parameters from gnmic command in dict format. This is helpful to read the final values. I could identify the considered path from "get-path" key.

**Comment by karimra** [comment] 2021-03-03 05:41
ok, I see what you mean. I will put it back

**Comment by krishprasad525** [comment] 2021-03-03 18:03
Thank you.

**Comment by krishprasad525** [comment] 2021-03-14 00:24
Thank you for enabling the debug option with required info. It's working fine. Still I see issue with gnmi prompt in latest build  :
get --path /interfaces/interface[name=ethernet 1/1]

checked with debug option, port number not considered
"get-path": "[/interfaces/interface[name=ethernet]",

**Comment by karimra** [comment] 2021-03-14 02:25
The path contains a space, so it needs to be quoted.

**Comment by krishprasad525** [comment] 2021-03-14 02:36
Tried with the following change, still same issue.
get --path /interfaces/interface[name="ethernet 1/1"]

from debug:
get-path": "[\"/interfaces/interface[name=\"\"ethernet\"]"

**Comment by krishprasad525** [comment] 2021-03-14 02:45
with entire path in quotes also it's not working :
get --path '/interfaces/interface[name=ethernet 1/1]'

from debug:
 "get-path": "['/interfaces/interface[name=ethernet 1/1]']",

**Comment by karimra** [comment] 2021-03-14 04:34
That output from debug is as expected, the path is supposed to be a list.
The issue is that prompt mode doesn't consider quotes so it doesn't strip the `'` from the path, 
it should be fixed in #345

**Comment by karimra** [comment] 2021-05-29 17:28
closing due to no response, feel free to reopen if the PR did not meet your request.

**Closed by karimra** 2021-05-29 17:28 UTC
